# Generated by Django 2.2.4 on 2019-08-15 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='机房区域')),
                ('manufactory', models.SmallIntegerField(choices=[(0, 'UCloud'), (1, 'Aliyun'), (2, '渔人码头26F'), (3, '渔人码头27F')], default=0, verbose_name='云服务商')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='机房地址')),
                ('project_name', models.CharField(max_length=32, verbose_name='所属项目')),
                ('email', models.CharField(blank=True, max_length=32, null=True, verbose_name='邮箱')),
                ('mobile', models.CharField(blank=True, max_length=16, null=True, verbose_name='联系方式')),
                ('comment', models.TextField(blank=True, max_length=256, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '机房区域',
                'verbose_name_plural': '机房区域',
                'unique_together': {('name', 'project_name')},
            },
        ),
        migrations.CreateModel(
            name='Host_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=32, verbose_name='主机名称')),
                ('etc', models.CharField(max_length=64, null=True, verbose_name='操作系统')),
                ('cpu', models.CharField(max_length=8, verbose_name='CPU核数')),
                ('memory', models.CharField(max_length=8, verbose_name='内存大小(MB)')),
                ('disk', models.CharField(max_length=16, verbose_name='磁盘大小(GB)')),
                ('ip_in', models.GenericIPAddressField(protocol='ipv4', unique=True, verbose_name='内网IP')),
                ('ip_out', models.GenericIPAddressField(blank=True, null=True, protocol='ipv4', verbose_name='外网IP')),
                ('status_choices', models.CharField(max_length=32, null=True, verbose_name='状态')),
                ('comment', models.TextField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '主机信息',
                'verbose_name_plural': '主机信息',
            },
        ),
        migrations.CreateModel(
            name='ULB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='ULB名称')),
                ('ulb_ip', models.GenericIPAddressField(protocol='ipv4', unique=True, verbose_name='基础网络')),
                ('service', models.CharField(max_length=218, null=True, verbose_name='后端节点')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'ULB',
                'verbose_name_plural': 'ULB',
            },
        ),
        migrations.CreateModel(
            name='EIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='EIP名称')),
                ('ip_address', models.GenericIPAddressField(protocol='ipv4', unique=True, verbose_name='IP地址')),
                ('bandwidth', models.CharField(max_length=16, verbose_name='带宽(MB)')),
                ('band_status_choices', models.CharField(max_length=16, null=True, verbose_name='绑定状态')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('data_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.DataCenter', verbose_name='机房区域')),
            ],
            options={
                'verbose_name': 'EIP',
                'verbose_name_plural': 'EIP',
            },
        ),
    ]
