# Generated by Django 2.2.4 on 2019-09-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20190815_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_user', models.CharField(max_length=50, verbose_name='登录用户')),
                ('src_ip', models.CharField(max_length=50, verbose_name='来源ip')),
                ('task_name', models.CharField(default='none', max_length=50, verbose_name='任务类型')),
                ('time_task_start', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('time_task_finished', models.DateTimeField(auto_now_add=True, null=True, verbose_name='结束时间')),
                ('cmd_object', models.CharField(max_length=50, null=True, verbose_name='操作对象')),
                ('cmd', models.CharField(max_length=200, verbose_name='执行命令')),
                ('cmd_result', models.CharField(max_length=10, verbose_name='命令结果')),
                ('cmd_detail', models.CharField(blank=True, max_length=5000, null=True, verbose_name='结果详情')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名')),
                ('path', models.CharField(max_length=50, verbose_name='项目路径')),
                ('online_status', models.CharField(blank=True, choices=[('0', '停用'), ('1', '激活')], max_length=30, null=True, verbose_name='激活状态')),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='作业名')),
                ('playbook', models.CharField(blank=True, max_length=100, null=True, verbose_name='playbook')),
                ('online_status', models.CharField(blank=True, choices=[('0', '停用'), ('1', '激活')], max_length=30, null=True, verbose_name='激活状态')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.project', verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='extravars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='变量组名')),
                ('vars', models.CharField(blank=True, max_length=150, null=True, verbose_name='配置参数')),
                ('online_status', models.CharField(blank=True, choices=[('0', '停用'), ('1', '激活')], max_length=30, null=True, verbose_name='激活状态')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.job', verbose_name='所属作业')),
            ],
        ),
    ]
