# Generated by Django 2.2.4 on 2019-11-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_extravars_history_job_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ulb',
            name='service',
        ),
        migrations.AddField(
            model_name='ulb',
            name='service1',
            field=models.CharField(max_length=218, null=True, verbose_name='后端节点1'),
        ),
        migrations.AddField(
            model_name='ulb',
            name='service2',
            field=models.CharField(max_length=218, null=True, verbose_name='后端节点2'),
        ),
        migrations.AddField(
            model_name='ulb',
            name='service3',
            field=models.CharField(max_length=218, null=True, verbose_name='后端节点3'),
        ),
        migrations.AddField(
            model_name='ulb',
            name='service4',
            field=models.CharField(max_length=218, null=True, verbose_name='后端节点4'),
        ),
        migrations.AddField(
            model_name='ulb',
            name='service5',
            field=models.CharField(max_length=218, null=True, verbose_name='后端节点4'),
        ),
    ]
